import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Provider from "@/components/Provider";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import { ModeToggle } from "@/components/theme/ThemeToggle";
//configDotenv({ path: path.resolve(process.cwd(), ".env-local") });
console.log(process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY);


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en" suppressHydrationWarning={true}>
            <Provider>
              <body className="bg-white dark:bg-gray-900 text-black dark:text-white">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                    >
                  {children}
                  <ModeToggle />
                </ThemeProvider>
              </body>
            </Provider>
      </html>
    </ClerkProvider>
  );
}
