import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Provider from "@/components/Provider";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
//configDotenv({ path: path.resolve(process.cwd(), ".env-local") });
console.log(process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY);


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  //dock?
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en" suppressHydrationWarning={true}>
            <Provider>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                    >
                  <body className="bg-gradient-to-b from-primary/10 to-primary/5">
                      {children}
                  </body>
                </ThemeProvider>
            </Provider>
      </html>
    </ClerkProvider>
  );
}
