import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    question: "What is TeachMagic?",
    answer: "TeachMagic is an AI-powered platform that helps educators create comprehensive slides and quizzes on any topic in minutes. It uses advanced AI to generate educational content, complete with custom images and interactive elements."
  },
  {
    question: "How does TeachMagic generate content?",
    answer: "TeachMagic uses state-of-the-art AI models to analyze your topic and generate relevant, accurate, and engaging educational content. It creates slides with titles, informative paragraphs, and custom AI-generated images, as well as interactive quizzes based on the slide content."
  },
  {
    question: "Can I customize the content generated by TeachMagic?",
    answer: "Yes, absolutely! While TeachMagic generates high-quality content automatically, you have full control to edit, customize, and refine the slides and quizzes to suit your specific needs and teaching style."
  },
  {
    question: "How can I export my created content?",
    answer: "TeachMagic allows you to easily export your slides to PowerPoint format and quizzes to PDF. This makes it simple to use your created content in various settings, both online and offline."
  },
  {
    question: "Is TeachMagic suitable for all grade levels?",
    answer: "Yes, TeachMagic is designed to adapt its content to various grade levels. When creating your content, you can specify the target grade level, and the AI will adjust the complexity and presentation of the material accordingly."
  }
];

export function FAQAccordion() {
  return (
    <div className="w-full max-w-3xl mx-auto bg-background/70 backdrop-blur-lg border border-border/40 rounded-2xl shadow-xl hover:shadow-2xl transition-all duration-300 overflow-hidden">
      <Accordion type="single" collapsible className="w-full">
        {faqs.map((faq, index) => (
          <AccordionItem 
            key={index} 
            value={`item-${index}`}
            className="border-b border-border/20 last:border-b-0"
          >
            <AccordionTrigger className="px-6 py-5 text-left font-semibold bg-gradient-to-r from-primary via-primary/80 to-secondary bg-clip-text text-transparent hover:from-primary/90 hover:to-secondary/90 transition-all duration-300 hover:bg-primary/5 group">
              <span className="group-hover:translate-x-1 transition-transform duration-300">
                {faq.question}
              </span>
            </AccordionTrigger>
            <AccordionContent className="px-6 pb-5 text-muted-foreground leading-relaxed bg-gradient-to-r from-transparent via-primary/2 to-transparent">
              {faq.answer}
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  );
}

